-- Product Catalog Service Schema
-- All primary keys are UUID values generated by the application.

CREATE TABLE products (
    id          UUID PRIMARY KEY,
    code        VARCHAR(64) UNIQUE NOT NULL,
    name        VARCHAR(255) NOT NULL,
    description TEXT,
    status      VARCHAR(32) NOT NULL DEFAULT 'active',
    created_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at  TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE plans (
    id          UUID PRIMARY KEY,
    product_id  UUID NOT NULL REFERENCES products(id) ON DELETE RESTRICT,
    code        VARCHAR(64) NOT NULL,
    name        VARCHAR(255) NOT NULL,
    description TEXT,
    status      VARCHAR(32) NOT NULL DEFAULT 'draft',
    version     INT NOT NULL DEFAULT 1,
    created_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE (product_id, code, version)
);

CREATE INDEX plans_product_id_status_idx ON plans (product_id, status);

-- Every active plan must have at least one active offer and price.
-- These cross-table rules are enforced by the application when activating a plan.
CREATE TABLE offers (
    id            UUID PRIMARY KEY,
    product_id    UUID NOT NULL REFERENCES products(id) ON DELETE RESTRICT,
    plan_id       UUID NOT NULL REFERENCES plans(id) ON DELETE RESTRICT,
    code          VARCHAR(64) NOT NULL,
    offer_type    VARCHAR(32) NOT NULL, -- free or paid
    billing_cycle VARCHAR(32) NOT NULL, -- free uses lifetime
    status        VARCHAR(32) NOT NULL DEFAULT 'draft',
    sort_order    INT NOT NULL DEFAULT 0,
    created_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE (plan_id, billing_cycle)
);

CREATE INDEX offers_product_plan_status_idx
    ON offers (product_id, plan_id, status);

CREATE TABLE prices (
    id              UUID PRIMARY KEY,
    offer_id        UUID NOT NULL REFERENCES offers(id) ON DELETE CASCADE,
    product_id      UUID NOT NULL REFERENCES products(id) ON DELETE RESTRICT,
    plan_id         UUID NOT NULL REFERENCES plans(id) ON DELETE RESTRICT,
    currency        VARCHAR(3) NOT NULL,
    amount          BIGINT NOT NULL, -- free is 0; paid is greater than 0
    status          VARCHAR(32) NOT NULL DEFAULT 'active',
    catalog_visible BOOLEAN NOT NULL DEFAULT false,
    catalog_data    JSONB NOT NULL, -- product, plan, offer and quota display data
    created_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE (offer_id, currency)
);

CREATE INDEX prices_catalog_idx
    ON prices (product_id, currency)
    WHERE status = 'active' AND catalog_visible = true;

CREATE TABLE quota_rules (
    id                     UUID PRIMARY KEY,
    product_id             UUID NOT NULL REFERENCES products(id) ON DELETE RESTRICT,
    plan_id                UUID NOT NULL REFERENCES plans(id) ON DELETE CASCADE,
    rule_key               VARCHAR(64) NOT NULL,
    limit_amount           BIGINT NOT NULL, -- greater than 0
    window_duration_seconds INT NOT NULL, -- greater than 0
    anchor_type            VARCHAR(32) NOT NULL, -- FIRST_USE or SUBSCRIPTION_DATE
    created_at             TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at             TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE (plan_id, rule_key, anchor_type)
);

CREATE INDEX quota_rules_product_plan_idx
    ON quota_rules (product_id, plan_id);
